services:
  - type: web
    name: stayhealthy
    runtime: node
    buildCommand: npm install && npm run build && npm run report
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
